---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 15