name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Message that will be displayed on users'' first issue'
        pr_message: |
    
          Em PRs de segurança automatizados (ex.: Dependabot + workflow de correção), a **descrição do PR** é preenchida automaticamente com o overview da correção **daquele** PR (audit, cadeias, diff e conclusão). Em PRs normais, use a descrição como preferir.
